# filepath: .github/workflows/build-extension.yml
name: Build Extension with Secrets

on:
  workflow_dispatch: # Allows manual triggering
  push:
    tags:
      - 'v*.*.*' # Or trigger on new tags for releases
      - 'v*.*.*-*' # Also trigger on pre-release tags like v1.0.0-alpha.1

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to create releases
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Updated to v4

      - name: Replace Placeholders
        run: |
          # Ensure the path to your file is correct
          # Replace Email Placeholder
          sed -i "s|'%%NCBI_API_EMAIL%%'|'${{ secrets.NCBI_API_EMAIL_SECRET }}'|g" ./content/ncbi_api_handler.js
          # Replace Tool Name Placeholder
          sed -i "s|'%%NCBI_TOOL_NAME%%'|'${{ secrets.NCBI_TOOL_NAME_SECRET }}'|g" ./content/ncbi_api_handler.js
        # For macOS runners, sed syntax is slightly different for multiple replacements or use separate commands:
        # sed -i '' "s|'%%NCBI_API_EMAIL%%'|'${{ secrets.NCBI_API_EMAIL_SECRET }}'|g" ./content/ncbi_api_handler.js
        # sed -i '' "s|'%%NCBI_TOOL_NAME%%'|'${{ secrets.NCBI_TOOL_NAME_SECRET }}'|g" ./content/ncbi_api_handler.js

      - name: Create ZIP Package
        run: |
          # Adjust the path and name of your extension files/directory
          zip -r mdpi-filter-extension.zip ./ -x ".git/*" ".github/*" "README.md" # Exclude unnecessary files

      - name: Upload Extension Artifact
        uses: actions/upload-artifact@v4 # Updated to v4
        with:
          name: mdpi-filter-extension-package
          path: mdpi-filter-extension.zip

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/') # Only run on tag pushes
        with:
          files: mdpi-filter-extension.zip # The file to upload as a release asset
          # The tag_name is automatically inferred from the Git tag that triggered the workflow
          # You can customize the release name and body if needed:
          # name: "Release ${{ github.ref_name }}"
          # body: "Automated release for ${{ github.ref_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}